import { createFileRoute, Link } from "@tanstack/react-router";
import { HeartHandshake, MapPinned, ShieldCheck, Users } from "lucide-react";
import { PageHero, SiteShell } from "@/components/site-shell";
import baliImage from "@/assets/bali.jpg";
import desertImage from "@/assets/desert-camp.jpg";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "About Al Yahmaa Tourism | Dubai Travel Experts" }, { name: "description", content: "Meet the Dubai travel team focused on personal service, honest guidance and memorable tailor-made journeys." },
  { property: "og:title", content: "About Al Yahmaa Tourism" }, { property: "og:description", content: "Travel planning built around listening, care and trusted local expertise." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: AboutPage });

function AboutPage() { return <SiteShell><main><PageHero eyebrow="Meet Al Yahmaa" title="Travel begins with someone who listens." text="We are a Dubai-based travel company built around a simple belief: the best journeys feel personal long before take-off." image={desertImage} imageAlt="Elegant private camp in the Dubai desert at sunset" />
  <section className="py-20 md:py-28"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-2 lg:items-center lg:px-8"><div className="relative"><img src={baliImage} alt="Green terraces in Bali" loading="lazy" width={1536} height={1024} className="aspect-[5/4] w-full rounded-sm object-cover"/><div className="absolute -bottom-6 right-5 bg-coral p-6 text-coral-foreground md:right-[-2rem]"><p className="font-display text-2xl">Made personal</p><p className="mt-1 text-sm opacity-80">Every trip. Every traveller.</p></div></div><div className="lg:pl-10"><p className="eyebrow">Our story</p><h2 className="section-title">Built in Dubai. Inspired by the world.</h2><p className="mt-6 leading-7 text-muted-foreground">Al Yahmaa Tourism helps families, couples, groups and businesses travel with more confidence. Our role is not simply to make a booking. It is to understand what matters to you, anticipate the details and create a journey that flows naturally.</p><p className="mt-4 leading-7 text-muted-foreground">From our office in Deira, we connect local insight with trusted partners across the world—while remaining close enough to answer when you need us.</p></div></div></section>
  <section className="bg-primary py-20 text-hero-foreground"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-2xl"><p className="eyebrow text-gold">What guides us</p><h2 className="font-display text-4xl sm:text-5xl">Service you can feel at every step</h2></div><div className="mt-12 grid gap-8 md:grid-cols-3">{[[HeartHandshake,"We listen first","Your preferences shape the plan—not the other way around."],[ShieldCheck,"We keep it clear","Thoughtful recommendations, transparent choices and no unnecessary complexity."],[MapPinned,"We stay connected","A Dubai-based team remains available before, during and after travel."]].map(([Icon,title,text]) => { const ValueIcon = Icon as typeof Users; return <article key={title as string} className="border-t border-hero-foreground/20 pt-7"><ValueIcon className="size-8 text-gold"/><h3 className="mt-6 text-xl font-semibold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-hero-foreground/65">{text as string}</p></article> })}</div></div></section>
  <section className="bg-surface py-24"><div className="mx-auto max-w-3xl px-5 text-center lg:px-8"><p className="font-display text-3xl italic leading-snug sm:text-4xl">The best journeys begin with a conversation, not a booking.</p><Link to="/contact" className="mt-8 text-sm font-semibold text-coral hover:text-coral/80">Meet your travel team</Link></div></section>
</main></SiteShell> }