import { createFileRoute } from "@tanstack/react-router";
import { Clock3, Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHero, SiteShell } from "@/components/site-shell";
import dubaiImage from "@/assets/dubai-creek-hero.jpg";

export const Route = createFileRoute("/contact")({ head: () => ({ meta: [
  { title: "Contact Al Yahmaa Tourism | Deira, Dubai" }, { name: "description", content: "Call, email, WhatsApp or visit Al Yahmaa Tourism at Zarooni Building, Al Marrar, Deira, Dubai." },
  { property: "og:title", content: "Plan Your Trip | Al Yahmaa Tourism" }, { property: "og:description", content: "Tell our Dubai travel specialists where you want to go." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: ContactPage });

function ContactPage() { return <SiteShell><main><PageHero eyebrow="Start a conversation" title="Where would you like to go?" text="Share your dates, destination ideas and the kind of trip you have in mind. Our team will help turn it into a clear, considered plan." image={dubaiImage} imageAlt="Dubai Creek and the city skyline at sunset" />
  <section className="py-20 md:py-28"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><div><p className="eyebrow">Speak with our team</p><h2 className="section-title">Personal travel advice, from Dubai</h2><p className="mt-5 leading-7 text-muted-foreground">For the fastest response, send us a WhatsApp message with your preferred destination, dates and number of travellers.</p><Button asChild size="lg" className="mt-7 rounded-sm bg-coral text-coral-foreground hover:bg-coral/90"><a href="https://wa.me/971585669200" target="_blank" rel="noreferrer"><MessageCircle />Chat on WhatsApp</a></Button></div><div className="grid gap-px bg-border sm:grid-cols-2">{[[Phone,"Call us","+971 58 566 9200","tel:+971585669200"],[Mail,"Email us","Alyahmaatourism@gmail.com","mailto:Alyahmaatourism@gmail.com"],[MapPin,"Visit us","301, Zarooni Building, Al Marrar, Deira, Dubai","https://maps.google.com/?q=Zarooni+Building+Al+Marrar+Deira+Dubai"],[Clock3,"Office hours","Monday–Saturday, 9:00–18:00","#"]].map(([Icon,label,value,href]) => { const ContactIcon = Icon as typeof Phone; return <a key={label as string} href={href as string} target={(href as string).startsWith("http") ? "_blank" : undefined} rel={(href as string).startsWith("http") ? "noreferrer" : undefined} className="group bg-surface p-7 transition-colors hover:bg-background"><ContactIcon className="size-7 text-coral"/><p className="mt-6 text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">{label as string}</p><p className="mt-2 font-semibold leading-6 group-hover:text-coral">{value as string}</p></a> })}</div></div></section>
  <section className="bg-primary py-20 text-hero-foreground"><div className="mx-auto max-w-5xl px-5 lg:px-8"><div className="text-center"><p className="eyebrow text-gold">Before you message</p><h2 className="font-display text-4xl sm:text-5xl">A few details help us plan faster</h2></div><div className="mt-10 grid gap-6 sm:grid-cols-3">{[["01","Where and when"],["02","Who is travelling"],["03","Your ideal budget"]].map(([n,title]) => <div key={n} className="border border-hero-foreground/15 p-6 text-center"><span className="font-display text-3xl text-gold">{n}</span><p className="mt-3 font-semibold">{title}</p></div>)}</div><p className="mt-7 text-center text-xs text-hero-foreground/50">Sample office hours are shown and can be updated with your confirmed schedule.</p></div></section>
</main></SiteShell> }